# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProjetWzorce-GithubViewer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProjetWzorce-GithubViewer
  pod 'Alamofire', '~> 4.0'
end
