@startuml composite_decision_tree
title Composite - pełna procedura decyzyjna

skinparam monochrome true
skinparam dpi 150

start

:Dane tworzą strukturę drzewiastą\n(relacja część-całość)?;
if (TAK) then (tak)
else (nie)
    :Brak hierarchii\nUżyj prostej listy lub słownika;
    stop
endif

:Ta sama operacja ma działać\nna liściu i gałęzi jednakowo?;
if (TAK) then (tak)
else (nie)
    :Różne API per poziom\nProsta klasa z listą dzieci;
    stop
endif

:Chcesz tylko rozszerzać zachowanie\npodatnego obiektu (owiniecie)?;
if (TAK) then (tak)
    :Dekorator\n(nie Composite);
    stop
else (nie)
endif

:Struktura stabilna, często nowe operacje?;
if (TAK) then (tak)
    :Composite + Visitor\n(Composite dla struktury,\nVisitor dla nowych operacji);
    stop
else (nie)
endif

:COMPOSITE jest odpowiedni;

:Klient musi wywoływać Add/Remove\nprzez interfejs Component?;
if (TAK) then (tak)
    :Transparent Composite\n(Add/Remove w interfejsie;\nlisc rzuca NotSupportedException);
else (nie)
    :Safe Composite\n(Add/Remove tylko w klasie Composite;\nbezpieczniejsze API);
endif

:Głębokość drzewa nieznana\nlub ryzyko przepełnienia stosu?;
if (TAK) then (tak)
    :Dodaj Iterator (BFS/DFS)\nzamiast czystej rekurencji;
else (nie)
    :Czysta rekurencja\nwystarczy;
endif

stop
@enduml

