# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Home Page', 'verbose_name_plural': 'Home Page'},
        ),
    ]
