# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170118_1923'),
    ]

    operations = [

    ]
